group:
  repos: |
    busybeaver/homelab-iac
    busybeaver/homelab-packages
    busybeaver/homelab-services
  files:
    - .github/linters/
    - .github/act_event.json
    - .github/CODEOWNERS
    - .github/justfile.shared
    - .lefthook/
    - public_key/
    - .actrc
    - .comet.json
    - .editorconfig
    - dprint.json
