---
extends: default

rules:
  line-length:
    max: 150
    level: warning
  document-start:
    level: warning
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
  comments:
    min-spaces-from-content: 2
