---
extends: default

rules:
  line-length:
    max: 150
    level: warning
  document-start:
    level: warning
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
