---
name: "Sync CI"

"on":
  # run on pushes to main
  push:
    branches:
      - main
      - gh-readonly-queue/main/**
  # run weekly on Monday at 12:00
  schedule:
    - cron: '0 12 * * 1'
  # run manually
  workflow_dispatch:

concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  sync_config:
    name: 'Sync Repository Configuration'
    runs-on: ubuntu-latest
    timeout-minutes: 15

    defaults:
      run:
        shell: bash
        working-directory: '.'

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: StepSecurity - Harden Github-hosted Runners
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920  # v2.20.0
        with:
          egress-policy: block
          disable-telemetry: true
          disable-sudo-and-containers: true
          allowed-endpoints: >
            api.github.com:443
            github.com:443
      - name: Git - Checkout
        id: git_checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803  # v6.1.0

      - name: GitHub - Generate App Token
        id: github_generate_app_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1  # v3.2.0
        with:
          app-id: ${{ secrets.REPOSITORY_ASSISTANT_APP_ID }}
          private-key: ${{ secrets.REPOSITORY_ASSISTANT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            homelab-iac
            homelab-packages
            homelab-services

      - name: GitHub - Sync Repository Configuration
        id: github_sync_repo_config
        uses: BetaHuhn/repo-file-sync-action@8b92be3375cf1d1b0cd579af488a9255572e4619  # v1.21.1
        with:
          GH_INSTALLATION_TOKEN: ${{ steps.github_generate_app_token.outputs.token }}
          PR_LABELS: configuration
          ASSIGNEES: busybeaver
          REVIEWERS: busybeaver
          COMMIT_PREFIX: "chore: "
          COMMIT_BODY: "Synchronize Repository Configuration"
          PR_BODY: "Synchronize Repository Configuration"
          GIT_EMAIL: >-
            ${{ secrets.REPOSITORY_ASSISTANT_APP_ID }}+repository-assistant[bot]@users.noreply.github.com
          GIT_USERNAME: repository-assistant[bot]
